### PR TITLE
vm: remove aot cache for security issues

### PR DESCRIPTION
**Pull request by yunwei37**
## Description

Remove AOT file cache for security issues. We may need a better design for it.

Related to #155

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Officeyutong** [comment]
What are the security issues?

**Comment by yunwei37** [comment]
> What are the security issues?

The AOT code is store in files and load without verify. If attacker modify the AOT code, then they can do anything in the runtime.

**Comment by Officeyutong** [comment]
> > What are the security issues?
> 
> The AOT code is store in files and load without verify. If attacker modify the AOT code, then they can do anything in the runtime.

Seems the security level is the same as modifying things in memory

**Comment by Officeyutong** [comment]
Did you remove the AOT cli?

**Pull request merged**
