### PR TITLE
bench: add new micro benchmark about maps and read/write userspace memory

### PR DESCRIPTION
**Pull request by yunwei37**
## Description

- Add benchmark about maps
- Improve bench document

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by yunwei37** [comment]
There are some performance problems we need to fix @Officeyutong

**Comment by Officeyutong** [comment]
> There are some performance problems we need to fix @Officeyutong 

What are behaviors of these issues?

**Comment by yunwei37** [comment]
What do you mean behavior?

**Comment by Officeyutong** [comment]
> What do you mean behavior?

What are the performance issues?

**Comment by yunwei37** [comment]
You can see from https://github.com/eunomia-bpf/bpftime/tree/master/benchmark#maps-operations


The benchmark without inline the map op function:

| Map Operation                      | Kernel (op - uprobe) (ns) | Userspace (op - uprobe) (ns) |
|------------------------------------|--------------------------:|-----------------------------:|
| __bench_hash_map_update            | 62827.533320              | 30296.051630                 |
| __bench_hash_map_lookup            | 15895.166920              | 23005.369380                 |
| __bench_hash_map_delete            | 19884.933980              | 13054.965970                 |
| __bench_array_map_update           | 9538.564600               | 6701.987970                  |
| __bench_array_map_lookup           |  183.155140               | 4305.515170                  |
| __bench_array_map_delete           |  216.088950               | 5987.507820                  |
| __bench_per_cpu_hash_map_update    | 33140.184290              | 95537.666900                 |
| __bench_per_cpu_hash_map_lookup    | 14089.238230              | 62913.855920                 |
| __bench_per_cpu_hash_map_delete    | 19753.563580              | 459826.428910                |
| __bench_per_cpu_array_map_update   |  8885.238500              | 25728.928170                 |
| __bench_per_cpu_array_map_lookup   |  1838.737400              | 8759.420790                  |
| __bench_per_cpu_array_map_delete   |  1867.948100              | 4802.404130                  |

**Comment by yunwei37** [comment]
Those costs are much higher than kernel eBPF maps

- per-cpu map op, include hash and array map
- array_map op (because we don't inline the map op)

**Pull request merged**
