### PR TITLE
runtime: implement userspace USDT

### LINKED ISSUE #135: [FEATURE] USDT support
In addition to current u(ret)probe support, it would be useful to support USDT.

**Describe the solution you'd like**

Support libbpf and bpftrace's [`usdt`](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#9-usdt-static-tracing-user-level)

**Describe alternatives you've considered**

Not quite sure. Maybe the current uprobe support can support usdt as well?

**Provide usage examples**

Trace usdt (such as the DTrace probes in OpenJDK https://github.com/openjdk/jdk/blob/e44276989fc6358065412be7567d0141c84f1282/src/hotspot/os/posix/dtrace/hotspot.d#L4)

### PR DESCRIPTION
**Pull request by Officeyutong**
Closes #135 

> On x86_64, a usdt tracepoint was corresponded to a nop instruction in the code. So we may hook this instruction to implement userspace USDT I've tested with GumInvocationListener of frida gum, it works well when attached to the address of the nop instruction.
> 
> So things we need to add USDT support are:
> 
> * logic to parse ELF and extract USDT definitions
> 
> Other logics would be similar to uprobe, and can even be reused

### CODE REVIEW

**Comment by Officeyutong** [comment]
According to libbpf's description to usdt https://github.com/libbpf/libbpf/blob/f81eef23b33c0dbf923e863a72ce51ea4d32e291/src/usdt.c#L24

The implementation of attach type usdt is just plain uprobes, attached to the specified nop instruction. libbpf handles all other things, including parse ELF and figure out tracepoints, resolving tracepoint arguments in the ebpf side, and so on, through two internal maps (__bpf_usdt_specs and __bpf_usdt_ip_to_spec_id, where the latter is only needed if bpf cookie is not supported)

So the thing we need to do is 
- Implement bpf cookie
- Test directly with usdt programs, and check if it can work. If it can't work, just fix bugs. We should have already supported USDT

**Comment by caizixian** [comment]
This looks great! Thanks!

Would you mind also checking whether this works with bpftrace (I remember seeing somewhere that you can use bpftrace with bpftime as the runtime)?

**Comment by Officeyutong** [comment]
> This looks great! Thanks!
> 
> Would you mind also checking whether this works with bpftrace (I remember seeing somewhere that you can use bpftrace with bpftime as the runtime)?

Ok, I'll also check it

**Comment by Officeyutong** [comment]
USDT is almost working now. Bpftrace is pending for testing

**Comment by yunwei37** [comment]
Maybe we can get this PR merged first if the libbpf example in `example/usdt_minimal/README.md` is working? 

After that, we can:
1. check and fix bpftrace
2. update documents.

**Comment by Officeyutong** [comment]
> Maybe we can get this PR merged first if the libbpf example in `example/usdt_minimal/README.md` is working?
> 
> After that, we can:
> 
> 1. check and fix bpftrace
> 2. update documents.

It's OK to merge now

**Review by yunwei37 — APPROVED** [review]

**Pull request merged**
