### PR TITLE
workflow to run attach tests

### LINKED ISSUE #236: [FEATURE] Add a workflow to run attach tests
I forget to add a workflow to run attach tests. The following targets are unit tests targets for attach implementation:
- bpftime_frida_uprobe_attach_tests 
- bpftime_syscall_trace_attach_tests 

Add a workflow to run them. Reference: https://github.com/eunomia-bpf/bpftime/blob/master/.github/workflows/test-llvm-jit.yml

### PR DESCRIPTION
**Pull request by Sanket-0510**
## Description

Fixes #236 

This change adds a CI job in github workflow to run 
- bpftime_frida_uprobe_attach_tests
- bpftime_syscall_trace_attach_tests

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by Officeyutong — CHANGES_REQUESTED** [review]
- Workflow for attach unit tests should be in a seperate file
- All unit tests should be run under both Ubuntu and Fedora

**Comment by Sanket-0510** [comment]
Hey @yunwei37 @Officeyutong you so much for your kind words, actually I am new to eBPF, trying to get myself familiar with the codebase. I overlooked a lot of things, indeed the implementation will be in separate files also the build and test command will differ. I overlooked the whole structure but now got an I idea, I will make changes soon.

**Comment by Sanket-0510** [comment]
Frida test workflow runs fine but the syscall one is failing. Is the target correct?

**Comment by Officeyutong** [comment]
> Frida test workflow runs fine but the syscall one is failing. Is the target correct?

The syscall trace test should be executed using sudo

**Review by Officeyutong — APPROVED** [review]

**Comment by Officeyutong** [comment]
Thank you!

**Comment by Sanket-0510** [comment]
> Thank you!

My pleasure 😊

**Pull request merged**
