### PR TITLE
ci: Fix CMakeLists.txt for llvm-jit to allow user define the llvm path

### LINKED ISSUE #187: [BUG] Support custom LLVM installation locations
My Fedora system's LLVM is too old (10). And I have to compile my own LLVM from source (version 14) and install under `/opt/llvm/`. Currently, the LLVM JIT build of bpftime only looks for system llvm locations, which won't work for my situation:

```
CMake Error at vm/llvm-jit/CMakeLists.txt:46 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Hopefully there is a way to configure the LLVM_DIR without editing any files.

### PR DESCRIPTION
**Pull request by Zheaoli**
## Description

Fixes #187 

In this PR, I make some changes following below:

1. Use the LLVM managed by the system package manager
2. Add `LLVM_FIND_PATH` to let people customize the LLVM path themself
3. Add `ENABLE_LLVM_SHARED` for some special distributions which are make the LLVM all dynamic lib (like Arch Linux, FYI  https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/commit/3e452a15b68d156a9ef5608e8f6e1870d192d954)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Officeyutong** [comment]
What does CMake option LLVM_PATH means?

**Comment by Officeyutong** [comment]
> What does CMake option LLVM_DIR means?
> 
> I think this option should be used to customize the user-defined llvm path, and the default search paths should be kept, since cmake is always unable to lookup the system wide installed llvm (check the CI)
> 
> ```
> CMake Error at vm/llvm-jit/CMakeLists.txt:46 (find_package):
>   Could not find a package configuration file provided by "LLVM" with any of
>   the following names:
> 
>     LLVMConfig.cmake
>     llvm-config.cmake
> 
>   Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
>   "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> ```

By the way, the search paths I wrote were default LLVM installed paths on Ubuntu and Fedora. CMake was unable to find them. So I kept them as default search paths, and users can customize LLVM install path through `LLVM_DIR`. 

```console
    /usr/lib/llvm-15/lib/cmake/llvm
    /usr/lib/llvm-14/lib/cmake/llvm
    /usr/lib/llvm-13/lib/cmake/llvm
    /usr/lib64/llvm15/lib/cmake/llvm
```

**Comment by Zheaoli** [comment]
@Officeyutong Hi, thanks for the comment, I can't quote your previous comment(would you mind to keep the discussion next time?)

After the discussion, I think it would be great keep only `find_package(LLVM REQUIRED CONFIG)` here. The developer could use the `LLVM_ROOT` or `-DLLVM_ROOT` to configure it. I think it would be better than hard code. 

Meanwhile, the PR have following thing to do:

1. Forbid LLVM-14
2. Make CI Happy

WDYT?

**Comment by Officeyutong** [comment]
> @Officeyutong Hi, thanks for the comment, I can't quote your previous comment(would you mind to keep the discussion next time?)
> 
> After the discussion, I think it would be great keep only `find_package(LLVM REQUIRED CONFIG)` here. The developer could use the `LLVM_ROOT` or `-DLLVM_ROOT` to configure it. I think it would be better than hard code.
> 
> Meanwhile, the PR have following thing to do:
> 
> 1. Forbid LLVM-14
> 2. Make CI Happy
> 
> WDYT?

In fact I don't know which is better, may be you should consult @yunwei37

**Comment by Officeyutong** [comment]
> > @Officeyutong Hi, thanks for the comment, I can't quote your previous comment(would you mind to keep the discussion next time?)
> > After the discussion, I think it would be great keep only `find_package(LLVM REQUIRED CONFIG)` here. The developer could use the `LLVM_ROOT` or `-DLLVM_ROOT` to configure it. I think it would be better than hard code.
> > Meanwhile, the PR have following thing to do:
> > 
> > 1. Forbid LLVM-14
> > 2. Make CI Happy
> > 
> > WDYT?
> 
> In fact I don't know which is better, may be you should consult @yunwei37

Note that thw following workflow should be modified:
- test-aot-cli.yml
- test-examples.yml
- test-llvm-jit.yml
- test-vm.yml

**Comment by yunwei37** [comment]
I think using find_package is ok. Thanks for your help!

**Comment by Zheaoli** [comment]
I think it could be a split PR. I will simplify the build process and the doc

**Comment by yunwei37** [comment]
Yes. It should be another issue. Thanks a lot!

**Comment by Zheaoli** [comment]
Also fix #203

**Review by yunwei37 — APPROVED** [review]

**Comment by yunwei37** [comment]
LGTM, Thanks!

**Pull request merged**
